# Frontend (React) configuration
[build]
  command = "npm run build"
  publish = "client/dist"

# Backend (Express.js) configuration
[build.server]
  command = "npm install && npm run start"
  publish = "server"

[build.environment]
  DB_URI = "mongodb+srv://b1shwas:falgun27@bookstore.cdeispi.mongodb.net/"
  PORT = "5555"
  CLOUDINARY_CLOUD_NAME = "b1shwas"
  CLOUDINARY_API_KEY = "698213982725262"
  CLOUDINARY_API_SECRET = "vhXREEtSNXpwrnFEbkdya18MRZ8"
  SECRET_KEY = "8f6a6ee7749b21bfd65cd1d260b5e547e40e2f7ff8a11cff7f7894b66bc21e81"
  ACCESS_TOKEN_EXPIRY = "1d"
  REFRESH_TOKEN_EXPIRY = "7d"

[build.processing]
  skip_processing = true

[[redirect]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200